/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;



import ControllerClass.ReviewerController;
import ETC.Papers;
import ETC.Reviews;
import static Gui.AuthorPapers.ID;
import User.Reviewer;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author XDpartypooper
 */
public class ReviewerPapers extends javax.swing.JFrame {
    static String name;
    static String ID;
    /**
     * Creates new form ReviewerPapers
     */
    public ReviewerPapers(String name,String ID) {
        this.name=name;
        this.ID=ID;
        initComponents();
       
        setLocationRelativeTo(null);
        workLoadRefresh();
        TableRefresh();
           
    }
    
    public void workLoadRefresh()
    {
        ReviewerController RC= new ReviewerController();
        String WL = RC.WorkLoadGetCon(ID);
        
        if(WL==null || WL=="" || WL=="0")
        {
             jLabel1.setText("No current prefered work load");
        }
        else
        {
            jLabel1.setText("Current prefered work load : "+WL+" papers");
        }
    }
    
    public void TableRefresh()
    {
        
         try {
            // TODO add your handling code here:
            //refresh Tables
            DefaultTableModel tbm1= (DefaultTableModel)jTable1.getModel();          
            DefaultTableModel tbm2= (DefaultTableModel)jTable2.getModel();
            tbm1.setRowCount(0);
            tbm2.setRowCount(0);
            ReviewerController RC= new ReviewerController();
            
            
            ArrayList<Papers> al = RC.ViewPaperCon(ID);
            for (int i=0; i< al.size();i++)
            {
                tbm1.addRow(al.get(i).GetPaper());
            }
            
            ArrayList<Reviews> al2 = RC.ReviewedPaperCon(ID);
            for (int i=0; i< al2.size();i++)
            {
                tbm2.addRow(al2.get(i).GetReviewDATA2());
            }
                      
        } catch (SQLException ex) {
            Logger.getLogger(ViewUsers.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
     public void ClosePanel()
    {
        setVisible(false);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });

        jButton4.setText("Main Menu");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Edit work load");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Current prefered work load : ????");

        jButton1.setText("Download Paper");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Submit / update / delete Review");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Paper Name", "Author", "Co Author", "Paper ID", "Reviewer"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(20);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(20);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(5);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(20);
        }

        jTabbedPane1.addTab("Allocated Papers", jScrollPane1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Paper Name", "Author", "Co Author", "Rating"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(3);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(3);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setPreferredWidth(3);
        }

        jTabbedPane1.addTab("Reviewed Paper", jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButton1)
                                .addGap(98, 98, 98)
                                .addComponent(jButton1)
                                .addGap(52, 52, 52)
                                .addComponent(jButton2))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jToggleButton1)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //Back to main menu
        Reviewer R= new Reviewer(name,ID);
        R.GotoReviewMenu(name,ID);
        ClosePanel();//close menu
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        try {
            // TODO add your handling code here:
            // edit work load
            JComboBox PTBox =new JComboBox();
            for (int i=0; i<31;i++)
            {
                PTBox.addItem(i);
            }
            JPanel myPanel = new JPanel();
            myPanel.add(Box.createHorizontalStrut(15)); // a spacer
            myPanel.add(new JLabel("Work load :"));
            myPanel.add(PTBox);
            int n = JOptionPane.showConfirmDialog(null, myPanel,"Choose Your prefered work load amount", JOptionPane.OK_CANCEL_OPTION);
                       
            String WL = PTBox.getSelectedItem().toString();//get name of co author

            ReviewerController RC= new ReviewerController();
            if(n == JOptionPane.OK_OPTION){
                int idNum=Integer.parseInt(WL);//convert 
            
                if(WL=="")
                {
                    WL=null;
                }
                else
                {
                    WL=String.format("%d",idNum);
                }
                RC.EditWorkLoadCon(WL,ID);
                workLoadRefresh();
            }     
        } catch (SQLException ex) {
            Logger.getLogger(ReviewerPapers.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        try {
            //download paper

            ReviewerController RC =new ReviewerController();
            JComboBox PTBox =new JComboBox();
            
            JPanel myPanel = new JPanel();
            
            ArrayList<Papers> al = RC.ViewPaperCon(ID);
            for (int i=0; i< al.size();i++)
            {
                PTBox.addItem(al.get(i).GetPName());
            }
            myPanel.add(new JLabel("Paper Name:"));
            myPanel.add(PTBox);
            myPanel.add(Box.createHorizontalStrut(15)); // a spacer
            int n=JOptionPane.showConfirmDialog(null, myPanel,"Select Paper you want to Download", JOptionPane.OK_CANCEL_OPTION);
            
            
            
            if(n == JOptionPane.OK_OPTION){ //
                String PaperName = PTBox.getSelectedItem().toString();//getPaperName
                try {
                    RC.DownloadPaperCon(PaperName);
                } catch (SQLException ex) {
                    Logger.getLogger(ReviewerPapers.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(ReviewerPapers.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            //submit / update
            ReviewerController RC =new ReviewerController();
            JComboBox PTBox =new JComboBox();
            
            JPanel myPanel = new JPanel();
            
            ArrayList<Papers> al = RC.ViewPaperCon(ID);
            for (int i=0; i< al.size();i++)
            {
                PTBox.addItem(al.get(i).GetPName());
            }
            myPanel.add(new JLabel("Paper Name:"));
            myPanel.add(PTBox);
            myPanel.add(Box.createHorizontalStrut(15)); // a spacer
            int n=JOptionPane.showConfirmDialog(null, myPanel,"Select paper you want to submit Review or update", JOptionPane.OK_CANCEL_OPTION);
            
            if(n == JOptionPane.OK_OPTION){ //
                    String PaperName = PTBox.getSelectedItem().toString();//getPaperName
        
                    JPanel myPanel1 = new JPanel();
                    JComboBox PTBox1 =new JComboBox();
                    JTextArea TA = new JTextArea(20,50);
                    PTBox1.addItem("");
                    for (int i=-3; i <4;i++)//1-5
                    {
                        PTBox1.addItem(i);
                    }
                    myPanel1.add(new JLabel("Rating(choose null to delete): \n (-3 for lowest rating, 3 for best rating)"));
                    myPanel1.add(PTBox1);
                    myPanel1.add(Box.createHorizontalStrut(15)); // a spacer
                    myPanel1.add(new JLabel("Review:"));
                    myPanel1.add(TA);
                    myPanel1.add(Box.createHorizontalStrut(15));
                    int x=JOptionPane.showConfirmDialog(null, myPanel1,"Enter your review", JOptionPane.OK_CANCEL_OPTION);
                    String Review = TA.getText();//getPaperName
                    String RatingString = PTBox1.getSelectedItem().toString();//getPaperName
                   
                    
                    if(RatingString.isEmpty())//delete
                    {
                        RC.DeleteReviewCon(PaperName);
                        TableRefresh();        
                    }
                    else if((Review.isEmpty()))
                    {
                        //error message pop up if empty
                        JOptionPane.showMessageDialog(null,"Nothing entered in Review","ERROR",JOptionPane.ERROR_MESSAGE);
                    }                
                    else if(x == JOptionPane.OK_OPTION)
                    { 
                        int Rating=Integer.parseInt(RatingString);
                        RC.ReviewerSUBUPCON(PaperName,Review,Rating);
                        TableRefresh();
                     }                
                } 
            
            
        } catch (SQLException ex) {
            Logger.getLogger(ReviewerPapers.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReviewerPapers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReviewerPapers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReviewerPapers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReviewerPapers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReviewerPapers(name,ID).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
