/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import ControllerClass.SystemAdminController;
import User.User;
import User.UserAccount;
import User.UserProfile;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author XDpartypooper
 */
public class ViewUsers extends javax.swing.JFrame {

    /**
     * Creates new form ViewUsers
     */
    public ViewUsers() throws SQLException {
        initComponents();
        setLocationRelativeTo(null);
        
        DefaultTableModel tbm1= (DefaultTableModel)jTable1.getModel();
        SystemAdminController SAC= new SystemAdminController();
        
      
        ArrayList<UserProfile> al = SAC.ViewAccCon();           
        for (int i=0; i< al.size();i++)
        {        
            tbm1.addRow(al.get(i).GetProfile());
        }
        
                       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton4.setText("Main Menu");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UserName", "Password", "Email", "Proftile Type", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(3);
        }

        jButton1.setText("Delete User");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update User");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Create User");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //Back to main menu
        new SystemAdminMenu().setVisible(true);
        ClosePanel();//close menu
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            //delete
            JFrame  f=new JFrame();
            SystemAdminController SAC= new SystemAdminController();
            String ID = JOptionPane.showInputDialog(f,"Enter the User ID you want to delete");
            
            int idNum=Integer.parseInt(ID);//convert last id from string to int
            ID=String.format("%03d",idNum);
            
            boolean CHECK=false;//check if ID exsist
            CHECK = SAC.IDExsistCon(ID);
            System.out.print(CHECK);
            if (CHECK==false)
            {
                JFrame e=new JFrame();
                JOptionPane.showMessageDialog(null,"No Such User","ERROR",JOptionPane.ERROR_MESSAGE);
                throw new SQLException();
            }
            
            if("001".equals(ID))
            {
                JFrame e=new JFrame();
                CHECK=false;
                JOptionPane.showMessageDialog(null,"YOU CANNOT DELETE ME I AM GOD","ERROR",JOptionPane.ERROR_MESSAGE);
                //cannot delete sys admin for obv reasons
                 throw new SQLException();
            }
                       
            if (CHECK==true)
            {   
                String name=SAC.GetNameCon(ID);

               JFrame c=new JFrame();
               int a=JOptionPane.showConfirmDialog(c,"Are you sure you want to delete User :"+name);

               if(a==JOptionPane.YES_OPTION)
                {
                    //final delete
                    SAC.DelAccCon(ID);//delete USER
                    JOptionPane.showMessageDialog(null,"User "+ name+" will be deleted!","User Deleted",JOptionPane.ERROR_MESSAGE);               
                }  
            }       
        } catch (SQLException ex) {
            Logger.getLogger(ViewUsers.class.getName()).log(Level.SEVERE, null, ex);
        }
    
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            //update
            JFrame  f=new JFrame();
            SystemAdminController SAC= new SystemAdminController();
            String ID = JOptionPane.showInputDialog(f,"Enter the User ID you want to update");
            
            int idNum=Integer.parseInt(ID);//convert last id from string to int
            ID=String.format("%03d",idNum);
            
            boolean CHECK=false;//check if ID exsist
            CHECK = SAC.IDExsistCon(ID);
            System.out.print(CHECK);
            if (CHECK==false)
            {
                JFrame e=new JFrame();
                JOptionPane.showMessageDialog(null,"No Such User","ERROR",JOptionPane.ERROR_MESSAGE);
                throw new SQLException();
            }
            
            if("001".equals(ID))
            {
                JFrame e=new JFrame();
                CHECK=false;
                JOptionPane.showMessageDialog(null,"Unable to change Origial System Admin to other Type of User","ERROR",JOptionPane.ERROR_MESSAGE);
                //cannot update sys admin for obv reasons
                 throw new SQLException();
            }
            
            if (CHECK==true)
            {
                JTextField UField = new JTextField(20);
                JTextField PField = new JTextField(20);
                JTextField EField = new JTextField(20);
                JComboBox PTBox =new JComboBox();

                ArrayList<UserProfile> al = SAC.GetProfileTypeCon();//get the profile tables
                for (int i=0; i< al.size();i++)
                {
                    PTBox.addItem(al.get(i).ReturnProfileType());
                }
                JPanel myPanel = new JPanel();
                myPanel.add(new JLabel("UserName:"));
                myPanel.add(UField);
                myPanel.add(Box.createHorizontalStrut(15)); // a spacer
                myPanel.add(new JLabel("password:"));
                myPanel.add(PField);
                myPanel.add(Box.createHorizontalStrut(15)); // a spacer
                myPanel.add(new JLabel("Email:"));
                myPanel.add(EField);
                myPanel.add(Box.createHorizontalStrut(15)); // a spacer
                myPanel.add(new JLabel("Profile Type:"));
                myPanel.add(PTBox);
             
                String name=SAC.GetNameCon(ID);
                JOptionPane.showConfirmDialog(null, myPanel,"Please Enter update data of user "+ name, JOptionPane.OK_CANCEL_OPTION);

                String UserName = UField.getText();//get username 
                String password = PField.getText();//get pass 
                String Email = EField.getText();//get Email 
                String ProfileType = PTBox.getSelectedItem().toString();//get profiletype 

                if((UserName.isEmpty()) || (password.isEmpty()) || (Email.isEmpty()) )
                {
                    //error message pop up if empty
                    JOptionPane.showMessageDialog(null,"Invalid, not values in Username,Password or Email","ERROR",JOptionPane.ERROR_MESSAGE);
                } 
                else
                {
                    SAC.UpdateAccountCon(UserName,password,Email,ProfileType,ID); 
                }       
            }       
        } catch (SQLException ex) {
            Logger.getLogger(ViewUsers.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            //refresh Tables
            DefaultTableModel tbm1= (DefaultTableModel)jTable1.getModel();
            tbm1.setRowCount(0);
            SystemAdminController SAC= new SystemAdminController();
            
            
            ArrayList<UserProfile> al = SAC.ViewAccCon();
            for (int i=0; i< al.size();i++)
            {
                tbm1.addRow(al.get(i).GetProfile());
            }
        } catch (SQLException ex) {
            Logger.getLogger(ViewUsers.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            // TODO add your handling code here:
            //Create User button
            JFrame  f=new JFrame();
            SystemAdminController SAC= new SystemAdminController();
            
            
            JTextField UField = new JTextField(20);
            JTextField EField = new JTextField(20);
            JComboBox PTBox =new JComboBox();
            
            ArrayList<UserProfile> al = SAC.GetProfileTypeCon();//get the profile tables
            for (int i=0; i< al.size();i++)
            {
                PTBox.addItem(al.get(i).ReturnProfileType());
            }
            JPanel myPanel = new JPanel();
            myPanel.add(new JLabel("UserName:"));
            myPanel.add(UField);
            myPanel.add(Box.createHorizontalStrut(15)); // a spacer
            myPanel.add(new JLabel("Email:"));
            myPanel.add(EField);
            myPanel.add(Box.createHorizontalStrut(15)); // a spacer
            myPanel.add(new JLabel("Profile Type:"));
            myPanel.add(PTBox);
            
            
            JOptionPane.showConfirmDialog(null, myPanel,"Please Enter details of User ", JOptionPane.OK_CANCEL_OPTION);
            
            String UserName = UField.getText();//get username
            String Email = EField.getText();//get Email
            String ProfileType = PTBox.getSelectedItem().toString();//get profiletype
            
            if((UserName.isEmpty()) || (Email.isEmpty()) )
            {
                //error message pop up if empty
                JFrame E=new JFrame();
                JOptionPane.showMessageDialog(E,"No username or Email Entered","ERROR",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                 UserAccount UA=new UserAccount();       
                 String Password=UA.passwordGenerator();//make random password
                 
                 //ask if want to make
                //check in db is username and email alr exsist
                //print out stuff
                System.out.println("USerName: "+UserName);
                System.out.println("Email: "+Email);
                System.out.println("Password: "+Password);
                System.out.println("ID: This will be auto generated from db");//need to finish this up
                System.out.println("ProfileType: "+ProfileType);

            
            try {
                SAC.AccCreCon(UserName,Password,Email,ProfileType);              
            } catch (SQLException ex) {
                Logger.getLogger(AccountCreate.class.getName()).log(Level.SEVERE, null, ex);
            }      
            }
        } catch (SQLException ex) {
            Logger.getLogger(ViewUsers.class.getName()).log(Level.SEVERE, null, ex);
        }     
    }//GEN-LAST:event_jButton5ActionPerformed
 public void ClosePanel()
    {
        setVisible(false);
        dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    
                    new ViewUsers().setVisible(true);
                     
                } catch (SQLException ex) {
                    Logger.getLogger(ViewUsers.class.getName()).log(Level.SEVERE, null, ex);
                    System.out.print("error");
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
